"""Model-side HTTP serving adapter for recurrent StreamVLN inference."""

from __future__ import annotations

import io
import threading
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any

import numpy as np
import torch
from PIL import Image, UnidentifiedImageError

from embodiinfer.engine.core import EngineCore
from embodiinfer.engine.serve.contracts import (
    ModelAction,
    ModelResult,
    RawImage,
    RawPolicyRequest,
    ServingAdapter,
)
from embodiinfer.types import ActionChunk, Observation, SessionKey

STREAMVLN_ACTION_SPACE = "streamvln.action_chunk.v1"
STREAMVLN_IMAGE_FIELD = "observation.images.rgb"


def _identifier(value: object, name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{name} must be a non-empty string")
    return value


def _image_name(value: str) -> str:
    stem = value.rsplit("/", 1)[-1]
    lowered = stem.lower()
    for suffix in (".jpeg", ".jpg", ".png"):
        if lowered.endswith(suffix):
            return stem[: -len(suffix)]
    return stem


def _load_raw_image(image: RawImage) -> torch.Tensor:
    if image.mime_type not in {"image/jpeg", "image/png"}:
        raise ValueError(f"unsupported image type {image.mime_type!r}")
    if not image.data:
        raise ValueError(f"{image.name} has empty image payload")
    try:
        with Image.open(io.BytesIO(image.data)) as opened:
            if opened.width * opened.height > 8_000_000:
                raise ValueError(f"{image.name} image has too many pixels")
            rgb = opened.convert("RGB")
            array = np.asarray(rgb, dtype=np.float32) / 255.0
    except (UnidentifiedImageError, OSError) as error:
        raise ValueError(f"{image.name} is not a valid encoded image") from error
    if array.ndim != 3 or array.shape[-1] != 3:
        raise ValueError(f"{image.name} is not an RGB image")
    return torch.from_numpy(array.transpose(2, 0, 1).copy())


@dataclass(frozen=True, slots=True)
class StreamVLNServingConfig:
    """Raw observation fields exposed to a StreamVLN HTTP service."""

    image_field: str = STREAMVLN_IMAGE_FIELD
    return_steps: int = 4

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any] | None) -> StreamVLNServingConfig:
        """Validate an adapter configuration generated by a deploy runtime."""

        config = {} if value is None else dict(value)
        image_fields = config.get("image_fields", (STREAMVLN_IMAGE_FIELD,))
        if isinstance(image_fields, (str, bytes)) or not isinstance(image_fields, Sequence):
            raise TypeError("image_fields must be a sequence")
        if len(image_fields) != 1:
            raise ValueError("StreamVLN serving requires exactly one image field")
        return_steps = config.get("return_steps", 4)
        if isinstance(return_steps, bool) or not isinstance(return_steps, int) or return_steps <= 0:
            raise ValueError("return_steps must be a positive integer")
        return cls(
            image_field=_identifier(image_fields[0], "image_field"),
            return_steps=return_steps,
        )


class StreamVLNServingAdapter(ServingAdapter):
    """Translate raw HTTP observations into transactional StreamVLN execution."""

    action_space = STREAMVLN_ACTION_SPACE

    def __init__(
        self,
        *,
        core: EngineCore,
        checkpoint: str | None = None,
        config: StreamVLNServingConfig | Mapping[str, Any] | None = None,
    ) -> None:
        del checkpoint
        if not core.policy.is_recurrent:
            raise TypeError("StreamVLN serving requires a recurrent policy")
        self._core = core
        self._policy = core.policy
        self._config = (
            config
            if isinstance(config, StreamVLNServingConfig)
            else StreamVLNServingConfig.from_mapping(config)
        )
        self._lock = threading.Lock()

    def capabilities(self) -> dict[str, Any]:
        """Describe the stable request and action contract exposed by the adapter."""

        return {
            "model": "streamvln",
            "action_space": self.action_space,
            "image_fields": [self._config.image_field],
            "return_steps": self._config.return_steps,
            "action_dim": 2,
            "recurrent": True,
            "execution_mode": "serialized_b1",
            "max_batch_size": 1,
        }

    def infer(self, request: RawPolicyRequest) -> ModelResult:
        """Execute one StreamVLN turn and commit its state under the HTTP session."""

        image = self._request_image(request.images)
        observation = Observation(
            images=_load_raw_image(image),
            state=torch.empty(0, dtype=torch.float32),
            instruction_tokens=torch.empty(0, dtype=torch.long),
            instruction=request.instruction,
            metadata={**dict(request.metadata), "step_id": request.step_id},
        )
        batch = self._policy.collate([observation], [request.request_id])
        with self._lock:
            chunks = self._core.execute(
                batch,
                session_ids=[self._session_key(request.session_id)],
            )
        if len(chunks) != 1:
            raise RuntimeError(f"StreamVLN returned {len(chunks)} action chunks; expected one")
        chunk = chunks[0]
        actions = self._valid_actions(chunk)
        timing = {name: float(value) for name, value in chunk.timing.items()}
        timing.setdefault("policy_ms", float(chunk.latency_ms))
        return ModelResult(
            action_space=self.action_space,
            actions=(
                ModelAction(
                    kind="action_chunk",
                    values={"data": actions.tolist()},
                ),
            ),
            timing=timing,
            policy_revision=str(chunk.policy_version),
        )

    def reset(self, session_id: str) -> None:
        """Invalidate the recurrent state associated with an HTTP session."""

        self._core.reset_sessions([self._session_key(session_id)])

    def _request_image(self, images: tuple[RawImage, ...]) -> RawImage:
        requested: dict[str, RawImage] = {}
        for image in images:
            name = _image_name(image.name)
            if name in requested:
                raise ValueError(f"duplicate image field {name!r}")
            requested[name] = image
        try:
            return requested[self._config.image_field]
        except KeyError as error:
            raise ValueError(f"missing requested image field {self._config.image_field!r}") from error

    def _valid_actions(self, chunk: ActionChunk) -> torch.Tensor:
        actions = torch.as_tensor(chunk.actions).detach().float().cpu()
        if actions.ndim != 2 or actions.shape[1] != 2:
            raise RuntimeError(f"StreamVLN returned invalid action shape {tuple(actions.shape)}")
        if chunk.trace is None or chunk.trace.action_mask is None:
            raise RuntimeError("StreamVLN action chunk is missing its action mask")
        mask = torch.as_tensor(chunk.trace.action_mask).detach().bool().cpu().reshape(-1)
        if mask.shape[0] != actions.shape[0]:
            raise RuntimeError("StreamVLN action mask does not match its action chunk")
        actions = actions[mask][: self._config.return_steps]
        if not actions.shape[0]:
            raise RuntimeError("StreamVLN returned no executable actions")
        if not bool(torch.isfinite(actions).all()):
            raise RuntimeError("StreamVLN returned non-finite actions")
        return actions

    @staticmethod
    def _session_key(session_id: str) -> SessionKey:
        return SessionKey(env_id=session_id, episode_id="http")


__all__ = [
    "STREAMVLN_ACTION_SPACE",
    "STREAMVLN_IMAGE_FIELD",
    "StreamVLNServingAdapter",
    "StreamVLNServingConfig",
]
